package com.sales.crm.model;

public enum ResourcePermissionEnum {
	
	CUSTOMER_CREATE(1),
	CUSTOMER_READ(2),
	CUSTOMER_UPDATE(3),
	CUSTOMER_DELETE(4),
	CUSTOMER_LIST(5),
	MANUFACTURER_CREATE(6),
	MANUFACTURER_READ(7),
	MANUFACTURER_UPDATE(8),
	MANUFACTURER_DELETE(9),
	MANUFACTURER_LIST(10),
	AREA_CREATE(11),
	AREA_READ(12),
	AREA_UPDATE(13),
	AREA_DELETE(14),
	AREA_LIST(15),
	BEAT_CREATE(16),
	BEAT_READ(17),
	BEAT_UPDATE(18),
	BEAT_DELETE(19),
	BEAT_LIST(20),
	BEAT_VIEW_ASSOCIATED_CUSTOMERS(21),
	BEAT_ASSOCIATE_CUSTOMERS(22),
	BEAT_EDIT_ASSOCIATED_CUSTOMERS(23),
	BEAT_DELETE_ASSOCIATED_CUSTOMERS(24),	
	RESELLER_CREATE(25),
	RESELLER_READ(26),
	RESELLER_UPDATE(27),
	RESELLER_DELETE(28),
	RESELLER_LIST(29),
	RESELLER_APPROVE(30),
	USER_CREATE(31),
	USER_READ(32),
	USER_UPDATE(33),
	USER_DELETE(34),
	USER_LIST(35),
	//USER_SCHEDULE_VISIT(36),
	USER_VIEW_ASSIGNED_BEATS(37),
	USER_ASSIGN_BEATS(38),
	USER_EDIT_ASSIGNED_BEATS(39),
	USER_DELETE_ASSIGNED_BEATS(40),
	//USER_VIEW_SCHEDULED_VISITS(41),
	ROLE_READ(42),
	ROLE_VIEW_RESOURCE_PERMISSION(43),
	ROLE_EDIT_RESOURCE_PERMISSION(44),
	ROLE_LIST(45),
	OTP_LIST(46),
	ORDER_LIST(47),
	ORDER_SCHEDULE_ORDER_BOOKING(48),
	ORDER_SCHEDULE_DELIVERY_BOOKING(49),
	ORDER_VIEW_SCHEDULED_ORDER_BOOKINGS(50),
	ORDER_VIEW_SCHEDULED_DELIVERY_BOOKINGS(51)
	;
	
	private int resourcePermID;
	
	ResourcePermissionEnum(int resourcePermID){
		this.resourcePermID = resourcePermID;
	}
	
	public int getResourcePermissionID(){
		return resourcePermID;
	}
}
